name: ci

on:
  push:
    branches:
      - amsl-master
  pull_request:
    branches:
      - amsl-master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros1-distro: humble
