name: ci

on:
  push:
    branches:
      - ros2
  pull_request:
    branches:
      - ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update
          apt install -yq --no-install-recommends python3-pip
          python3 -m pip install colcon-lcov-result \
            colcon-coveragepy-result \
            colcon-mixin
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
